declare const React: any
declare const useState: Function
declare const useEffect: Function
declare const useContext: Function
declare const useReducer: Function
declare const useCallback: Function
declare const useMemo: Function
declare const useRef: Function
declare const useImperativeHandle: Function
declare const useLayoutEffect: Function
declare const useDebugValue: Function