export declare const React: any
export declare const useState: Function
export declare const useEffect: Function
export declare const useContext: Function
export declare const useReducer: Function
export declare const useCallback: Function
export declare const useMemo: Function
export declare const useRef: Function
export declare const useImperativeHandle: Function
export declare const useLayoutEffect: Function
export declare const useDebugValue: Function